version = 1

[[annotations]]
path = [
    "fastlane/metadata/**",
    "fastlane/screenshots/**",
    "Figures/**",
    "LLMonFHIR.xcodeproj/**",
    "LLMonFHIR/Resources/**",
    "LLMonFHIR/Supporting Files/**",
    "LLMonFHIRShared/Sources/LLMonFHIRShared/Resources/**",
    "LLMonFHIRShared/Tests/LLMonFHIRSharedTests/Resources/*"
]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"
